/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.maersk.geography.smds.operations.msk;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Display business defined area information. Example : North India,West & Central Asia and so on */
@org.apache.avro.specific.AvroGenerated
public class bda extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2235018767292051351L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"bda\",\"namespace\":\"com.maersk.geography.smds.operations.msk\",\"doc\":\"Display business defined area information. Example : North India,West & Central Asia and so on\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"bdaType\",\"type\":\"string\"},{\"name\":\"alternateCodes\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"bdaAlternateCode\",\"doc\":\"BDA AlternateCode details\",\"fields\":[{\"name\":\"codeType\",\"type\":\"string\"},{\"name\":\"code\",\"type\":\"string\"}]}}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<bda> ENCODER =
      new BinaryMessageEncoder<bda>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<bda> DECODER =
      new BinaryMessageDecoder<bda>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<bda> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<bda> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<bda> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<bda>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this bda to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a bda from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a bda instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static bda fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence name;
  private java.lang.CharSequence type;
  private java.lang.CharSequence bdaType;
  private java.util.List<com.maersk.geography.smds.operations.msk.bdaAlternateCode> alternateCodes;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public bda() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param type The new value for type
   * @param bdaType The new value for bdaType
   * @param alternateCodes The new value for alternateCodes
   */
  public bda(java.lang.CharSequence name, java.lang.CharSequence type, java.lang.CharSequence bdaType, java.util.List<com.maersk.geography.smds.operations.msk.bdaAlternateCode> alternateCodes) {
    this.name = name;
    this.type = type;
    this.bdaType = bdaType;
    this.alternateCodes = alternateCodes;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return type;
    case 2: return bdaType;
    case 3: return alternateCodes;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: type = (java.lang.CharSequence)value$; break;
    case 2: bdaType = (java.lang.CharSequence)value$; break;
    case 3: alternateCodes = (java.util.List<com.maersk.geography.smds.operations.msk.bdaAlternateCode>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.CharSequence getType() {
    return type;
  }


  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.CharSequence value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'bdaType' field.
   * @return The value of the 'bdaType' field.
   */
  public java.lang.CharSequence getBdaType() {
    return bdaType;
  }


  /**
   * Sets the value of the 'bdaType' field.
   * @param value the value to set.
   */
  public void setBdaType(java.lang.CharSequence value) {
    this.bdaType = value;
  }

  /**
   * Gets the value of the 'alternateCodes' field.
   * @return The value of the 'alternateCodes' field.
   */
  public java.util.List<com.maersk.geography.smds.operations.msk.bdaAlternateCode> getAlternateCodes() {
    return alternateCodes;
  }


  /**
   * Sets the value of the 'alternateCodes' field.
   * @param value the value to set.
   */
  public void setAlternateCodes(java.util.List<com.maersk.geography.smds.operations.msk.bdaAlternateCode> value) {
    this.alternateCodes = value;
  }

  /**
   * Creates a new bda RecordBuilder.
   * @return A new bda RecordBuilder
   */
  public static com.maersk.geography.smds.operations.msk.bda.Builder newBuilder() {
    return new com.maersk.geography.smds.operations.msk.bda.Builder();
  }

  /**
   * Creates a new bda RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new bda RecordBuilder
   */
  public static com.maersk.geography.smds.operations.msk.bda.Builder newBuilder(com.maersk.geography.smds.operations.msk.bda.Builder other) {
    if (other == null) {
      return new com.maersk.geography.smds.operations.msk.bda.Builder();
    } else {
      return new com.maersk.geography.smds.operations.msk.bda.Builder(other);
    }
  }

  /**
   * Creates a new bda RecordBuilder by copying an existing bda instance.
   * @param other The existing instance to copy.
   * @return A new bda RecordBuilder
   */
  public static com.maersk.geography.smds.operations.msk.bda.Builder newBuilder(com.maersk.geography.smds.operations.msk.bda other) {
    if (other == null) {
      return new com.maersk.geography.smds.operations.msk.bda.Builder();
    } else {
      return new com.maersk.geography.smds.operations.msk.bda.Builder(other);
    }
  }

  /**
   * RecordBuilder for bda instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<bda>
    implements org.apache.avro.data.RecordBuilder<bda> {

    private java.lang.CharSequence name;
    private java.lang.CharSequence type;
    private java.lang.CharSequence bdaType;
    private java.util.List<com.maersk.geography.smds.operations.msk.bdaAlternateCode> alternateCodes;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.maersk.geography.smds.operations.msk.bda.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.bdaType)) {
        this.bdaType = data().deepCopy(fields()[2].schema(), other.bdaType);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.alternateCodes)) {
        this.alternateCodes = data().deepCopy(fields()[3].schema(), other.alternateCodes);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing bda instance
     * @param other The existing instance to copy.
     */
    private Builder(com.maersk.geography.smds.operations.msk.bda other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.bdaType)) {
        this.bdaType = data().deepCopy(fields()[2].schema(), other.bdaType);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.alternateCodes)) {
        this.alternateCodes = data().deepCopy(fields()[3].schema(), other.alternateCodes);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.maersk.geography.smds.operations.msk.bda.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.maersk.geography.smds.operations.msk.bda.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.CharSequence getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public com.maersk.geography.smds.operations.msk.bda.Builder setType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.type = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public com.maersk.geography.smds.operations.msk.bda.Builder clearType() {
      type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'bdaType' field.
      * @return The value.
      */
    public java.lang.CharSequence getBdaType() {
      return bdaType;
    }


    /**
      * Sets the value of the 'bdaType' field.
      * @param value The value of 'bdaType'.
      * @return This builder.
      */
    public com.maersk.geography.smds.operations.msk.bda.Builder setBdaType(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.bdaType = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'bdaType' field has been set.
      * @return True if the 'bdaType' field has been set, false otherwise.
      */
    public boolean hasBdaType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'bdaType' field.
      * @return This builder.
      */
    public com.maersk.geography.smds.operations.msk.bda.Builder clearBdaType() {
      bdaType = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'alternateCodes' field.
      * @return The value.
      */
    public java.util.List<com.maersk.geography.smds.operations.msk.bdaAlternateCode> getAlternateCodes() {
      return alternateCodes;
    }


    /**
      * Sets the value of the 'alternateCodes' field.
      * @param value The value of 'alternateCodes'.
      * @return This builder.
      */
    public com.maersk.geography.smds.operations.msk.bda.Builder setAlternateCodes(java.util.List<com.maersk.geography.smds.operations.msk.bdaAlternateCode> value) {
      validate(fields()[3], value);
      this.alternateCodes = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'alternateCodes' field has been set.
      * @return True if the 'alternateCodes' field has been set, false otherwise.
      */
    public boolean hasAlternateCodes() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'alternateCodes' field.
      * @return This builder.
      */
    public com.maersk.geography.smds.operations.msk.bda.Builder clearAlternateCodes() {
      alternateCodes = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public bda build() {
      try {
        bda record = new bda();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.type = fieldSetFlags()[1] ? this.type : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.bdaType = fieldSetFlags()[2] ? this.bdaType : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.alternateCodes = fieldSetFlags()[3] ? this.alternateCodes : (java.util.List<com.maersk.geography.smds.operations.msk.bdaAlternateCode>) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<bda>
    WRITER$ = (org.apache.avro.io.DatumWriter<bda>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<bda>
    READER$ = (org.apache.avro.io.DatumReader<bda>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.name);

    out.writeString(this.type);

    out.writeString(this.bdaType);

    if (this.alternateCodes == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      long size0 = this.alternateCodes.size();
      out.writeArrayStart();
      out.setItemCount(size0);
      long actualSize0 = 0;
      for (com.maersk.geography.smds.operations.msk.bdaAlternateCode e0: this.alternateCodes) {
        actualSize0++;
        out.startItem();
        e0.customEncode(out);
      }
      out.writeArrayEnd();
      if (actualSize0 != size0)
        throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.type = in.readString(this.type instanceof Utf8 ? (Utf8)this.type : null);

      this.bdaType = in.readString(this.bdaType instanceof Utf8 ? (Utf8)this.bdaType : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.alternateCodes = null;
      } else {
        long size0 = in.readArrayStart();
        java.util.List<com.maersk.geography.smds.operations.msk.bdaAlternateCode> a0 = this.alternateCodes;
        if (a0 == null) {
          a0 = new SpecificData.Array<com.maersk.geography.smds.operations.msk.bdaAlternateCode>((int)size0, SCHEMA$.getField("alternateCodes").schema().getTypes().get(1));
          this.alternateCodes = a0;
        } else a0.clear();
        SpecificData.Array<com.maersk.geography.smds.operations.msk.bdaAlternateCode> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.maersk.geography.smds.operations.msk.bdaAlternateCode>)a0 : null);
        for ( ; 0 < size0; size0 = in.arrayNext()) {
          for ( ; size0 != 0; size0--) {
            com.maersk.geography.smds.operations.msk.bdaAlternateCode e0 = (ga0 != null ? ga0.peek() : null);
            if (e0 == null) {
              e0 = new com.maersk.geography.smds.operations.msk.bdaAlternateCode();
            }
            e0.customDecode(in);
            a0.add(e0);
          }
        }
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 1:
          this.type = in.readString(this.type instanceof Utf8 ? (Utf8)this.type : null);
          break;

        case 2:
          this.bdaType = in.readString(this.bdaType instanceof Utf8 ? (Utf8)this.bdaType : null);
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.alternateCodes = null;
          } else {
            long size0 = in.readArrayStart();
            java.util.List<com.maersk.geography.smds.operations.msk.bdaAlternateCode> a0 = this.alternateCodes;
            if (a0 == null) {
              a0 = new SpecificData.Array<com.maersk.geography.smds.operations.msk.bdaAlternateCode>((int)size0, SCHEMA$.getField("alternateCodes").schema().getTypes().get(1));
              this.alternateCodes = a0;
            } else a0.clear();
            SpecificData.Array<com.maersk.geography.smds.operations.msk.bdaAlternateCode> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.maersk.geography.smds.operations.msk.bdaAlternateCode>)a0 : null);
            for ( ; 0 < size0; size0 = in.arrayNext()) {
              for ( ; size0 != 0; size0--) {
                com.maersk.geography.smds.operations.msk.bdaAlternateCode e0 = (ga0 != null ? ga0.peek() : null);
                if (e0 == null) {
                  e0 = new com.maersk.geography.smds.operations.msk.bdaAlternateCode();
                }
                e0.customDecode(in);
                a0.add(e0);
              }
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










